### ISSUE TITLE
502 error after updating `nginx-proxy`

### ISSUE THREAD

**Issue by delawski** [xwp/xwp-vip-site-template#160]
It seems that the `nginx-proxy@1.0.1` breaks the boilerplate.

On one of the projects, when trying to access the local environment, I kept getting a 502 Bad Gateway error.

@piotr-bajer found out that reverting #149 (degrade `jwilder/nginx-proxy` to `0.9.0`) fixes the issue.

_Originally posted by @delawski in https://github.com/xwp/xwp-vip-site-template/issues/149#issuecomment-1209327209_

**Comment by piotr-bajer** [comment]
Let's use this PR as a fix: https://github.com/xwp/xwp-vip-site-template/pull/162
